// Celebrities grouped by category. Each entry: the Wikipedia page title
// (used to fetch the photo) and optional extra accepted answers.
// "deep" names (real or birth names, mostly) are lesser known and score a bonus.
// "people" is the Human mode list and "hard" is the Perfect Human Specimen list.
const CATEGORIES = {
  movies: {
    label: "Movies & TV",
    emoji: "🎬",
    people: [
      { wiki: "Tom_Hanks" },
      { wiki: "Leonardo_DiCaprio", aliases: ["Leo DiCaprio"] },
      { wiki: "Dwayne_Johnson", aliases: ["The Rock"] },
      { wiki: "Brad_Pitt" },
      { wiki: "Angelina_Jolie" },
      { wiki: "Keanu_Reeves" },
      { wiki: "Scarlett_Johansson" },
      { wiki: "Morgan_Freeman" },
      { wiki: "Meryl_Streep" },
      { wiki: "Will_Smith" },
      { wiki: "Zendaya", deep: ["Zendaya Coleman"] },
      { wiki: "Timothée_Chalamet", aliases: ["Timothee Chalamet"] },
      { wiki: "Margot_Robbie" },
      { wiki: "Ryan_Gosling" },
      { wiki: "Ryan_Reynolds" },
      { wiki: "Emma_Watson" },
      { wiki: "Daniel_Radcliffe" },
      { wiki: "Robert_Downey_Jr.", aliases: ["Robert Downey Jr", "RDJ", "Robert Downey"] },
      { wiki: "Chris_Hemsworth" },
      { wiki: "Tom_Cruise", deep: ["Thomas Mapother"] },
      { wiki: "Denzel_Washington" },
      { wiki: "Samuel_L._Jackson", aliases: ["Samuel Jackson", "Samuel L Jackson"] },
      { wiki: "Jennifer_Lawrence" },
      { wiki: "Natalie_Portman", deep: ["Natalie Hershlag"] },
      { wiki: "Pedro_Pascal" },
      { wiki: "Keira_Knightley" },
      { wiki: "Hugh_Jackman" },
      { wiki: "Johnny_Depp" },
      { wiki: "Nicole_Kidman" },
      { wiki: "Jackie_Chan", deep: ["Chan Kong-sang"] },
      { wiki: "Tom_Holland" },
      { wiki: "Jennifer_Aniston" },
      { wiki: "Chris_Pratt" },
      { wiki: "Julia_Roberts" },
      { wiki: "George_Clooney" },
      { wiki: "Matt_Damon" },
      { wiki: "Sandra_Bullock" },
      { wiki: "Harrison_Ford" },
      { wiki: "Arnold_Schwarzenegger", aliases: ["Arnold", "Schwarzenegger"] },
      { wiki: "Sydney_Sweeney" },
      { wiki: "Anne_Hathaway" },
      { wiki: "Florence_Pugh" },
      { wiki: "Jason_Momoa" },
      { wiki: "Cillian_Murphy" },
      { wiki: "Emma_Stone", deep: ["Emily Stone"] },
      { wiki: "Viola_Davis" },
      { wiki: "Idris_Elba" },
      { wiki: "Chris_Evans_(actor)" },
      { wiki: "Mark_Ruffalo" },
      { wiki: "Benedict_Cumberbatch" },
      { wiki: "Tom_Hardy" },
      { wiki: "Christian_Bale" },
      { wiki: "Jim_Carrey" },
      { wiki: "Adam_Sandler" },
      { wiki: "Eddie_Murphy" },
      { wiki: "Kevin_Hart" },
      { wiki: "Halle_Berry" },
      { wiki: "Charlize_Theron" },
      { wiki: "Kate_Winslet" },
      { wiki: "Cate_Blanchett" },
      { wiki: "Nicolas_Cage", deep: ["Nicolas Coppola"] },
      { wiki: "Al_Pacino" },
      { wiki: "Robert_De_Niro", aliases: ["De Niro"] },
      { wiki: "Jenna_Ortega" },
      { wiki: "Millie_Bobby_Brown" },
      { wiki: "Austin_Butler" },
      { wiki: "Paul_Rudd" },
      { wiki: "Steve_Carell" },
      { wiki: "Marilyn_Monroe", deep: ["Norma Jeane Mortenson", "Norma Jeane Baker", "Norma Jean"] },
      { wiki: "Audrey_Hepburn" },
      { wiki: "Charlie_Chaplin" },
    ],
    // Hard mode: recognizable, but not household names.
    hard: [
      { wiki: "Steve_Buscemi" },
      { wiki: "Willem_Dafoe" },
      { wiki: "Frances_McDormand" },
      { wiki: "J._K._Simmons", aliases: ["JK Simmons", "J K Simmons"] },
      { wiki: "Stanley_Tucci" },
      { wiki: "Tilda_Swinton" },
      { wiki: "John_Goodman" },
      { wiki: "Christopher_Walken" },
      { wiki: "Jeff_Goldblum" },
      { wiki: "Bill_Murray" },
      { wiki: "Gary_Oldman" },
      { wiki: "Ralph_Fiennes" },
      { wiki: "Helen_Mirren" },
      { wiki: "Judi_Dench" },
      { wiki: "Maggie_Smith" },
      { wiki: "Michelle_Yeoh" },
      { wiki: "Ke_Huy_Quan", deep: ["Jonathan Ke Quan"] },
      { wiki: "Oscar_Isaac" },
      { wiki: "Adam_Driver" },
      { wiki: "Mahershala_Ali" },
      { wiki: "Lupita_Nyong'o", aliases: ["Lupita Nyongo", "Lupita"] },
      { wiki: "Daniel_Kaluuya" },
      { wiki: "Jodie_Comer" },
      { wiki: "Paul_Mescal" },
      { wiki: "Barry_Keoghan" },
      { wiki: "Anya_Taylor-Joy", aliases: ["Anya Taylor Joy"] },
      { wiki: "Saoirse_Ronan" },
      { wiki: "Jessica_Chastain" },
      { wiki: "Amy_Adams" },
      { wiki: "Rachel_McAdams" },
      { wiki: "Octavia_Spencer" },
      { wiki: "Forest_Whitaker" },
      { wiki: "Javier_Bardem" },
      { wiki: "Penélope_Cruz", aliases: ["Penelope Cruz"] },
      { wiki: "Mads_Mikkelsen" },
      { wiki: "Christoph_Waltz" },
      { wiki: "Bryan_Cranston" },
      { wiki: "Aaron_Paul" },
      { wiki: "Jon_Hamm" },
      { wiki: "Elisabeth_Moss" },
      { wiki: "Bob_Odenkirk" },
      { wiki: "Giancarlo_Esposito" },
      { wiki: "Jeremy_Strong" },
      { wiki: "Kieran_Culkin" },
      { wiki: "Jeremy_Allen_White" },
      { wiki: "Ayo_Edebiri" },
      { wiki: "Danny_Trejo" },
      { wiki: "Sigourney_Weaver" },
      { wiki: "Jamie_Lee_Curtis" },
      { wiki: "Glenn_Close" },
      { wiki: "Laura_Dern" },
      { wiki: "Toni_Collette" },
      { wiki: "Kathy_Bates" },
      { wiki: "Woody_Harrelson" },
      { wiki: "Sam_Rockwell" },
      { wiki: "Benicio_del_Toro" },
      { wiki: "Ewan_McGregor" },
      { wiki: "Jude_Law" },
      { wiki: "Colin_Firth" },
      { wiki: "Hugh_Grant" },
      { wiki: "Liam_Neeson" },
      { wiki: "Anthony_Hopkins" },
      { wiki: "Ian_McKellen" },
      { wiki: "Patrick_Stewart" },
      { wiki: "Gene_Hackman" },
      { wiki: "Jack_Nicholson" },
      { wiki: "Dustin_Hoffman" },
      { wiki: "Clint_Eastwood" },
      { wiki: "Grace_Kelly" },
      { wiki: "Humphrey_Bogart" },
      { wiki: "James_Dean" },
      { wiki: "Ingrid_Bergman" },
      { wiki: "Paul_Newman" },
      { wiki: "Sophia_Loren", deep: ["Sofia Scicolone"] },
      { wiki: "Quentin_Tarantino" },
      { wiki: "Christopher_Nolan" },
      { wiki: "Greta_Gerwig" },
      { wiki: "Martin_Scorsese" },
      { wiki: "Steven_Spielberg" },
      { wiki: "Wes_Anderson" },
      { wiki: "Guillermo_del_Toro" },
      { wiki: "Bong_Joon_Ho", aliases: ["Bong Joon-ho"] },
    ],
  },
  music: {
    label: "Music",
    emoji: "🎤",
    people: [
      { wiki: "Taylor_Swift" },
      { wiki: "Beyoncé", aliases: ["Beyonce", "Queen B"], deep: ["Beyoncé Knowles"] },
      { wiki: "Rihanna", deep: ["Robyn Fenty"] },
      { wiki: "Lady_Gaga", deep: ["Stefani Germanotta"] },
      { wiki: "Jennifer_Lopez", aliases: ["J.Lo", "JLo"] },
      { wiki: "Ed_Sheeran" },
      { wiki: "Adele", deep: ["Adele Adkins"] },
      { wiki: "Billie_Eilish" },
      { wiki: "Ariana_Grande" },
      { wiki: "Justin_Bieber" },
      { wiki: "Bruno_Mars", deep: ["Peter Hernandez"] },
      { wiki: "Snoop_Dogg", aliases: ["Snoop"], deep: ["Calvin Broadus"] },
      { wiki: "Selena_Gomez" },
      { wiki: "Harry_Styles" },
      { wiki: "Dua_Lipa" },
      { wiki: "Paul_McCartney" },
      { wiki: "Dolly_Parton" },
      { wiki: "Shakira", deep: ["Shakira Mebarak"] },
      { wiki: "Bad_Bunny", deep: ["Benito Martínez Ocasio", "Benito Martínez"] },
      { wiki: "Michael_Jackson" },
      { wiki: "Drake_(musician)", deep: ["Aubrey Graham"] },
      { wiki: "Eminem", deep: ["Marshall Mathers"] },
      { wiki: "Kanye_West", aliases: ["Kanye", "Ye"] },
      { wiki: "Madonna", deep: ["Madonna Ciccone"] },
      { wiki: "Elton_John", deep: ["Reginald Dwight"] },
      { wiki: "Olivia_Rodrigo" },
      { wiki: "Sabrina_Carpenter" },
      { wiki: "Post_Malone", deep: ["Austin Post"] },
      { wiki: "Katy_Perry", deep: ["Katheryn Hudson", "Katy Hudson"] },
      { wiki: "Miley_Cyrus", deep: ["Destiny Hope Cyrus"] },
      { wiki: "Mick_Jagger" },
      { wiki: "Nicki_Minaj", deep: ["Onika Maraj"] },
      { wiki: "The_Weeknd", aliases: ["Weeknd"], deep: ["Abel Tesfaye"] },
      { wiki: "Elvis_Presley", aliases: ["Elvis"] },
      { wiki: "Freddie_Mercury", deep: ["Farrokh Bulsara"] },
      { wiki: "Kendrick_Lamar", aliases: ["Kendrick"] },
      { wiki: "Bob_Marley" },
      { wiki: "Bob_Dylan", deep: ["Robert Zimmerman"] },
      { wiki: "John_Lennon" },
      { wiki: "David_Bowie", deep: ["David Jones"] },
      { wiki: "Prince_(musician)", deep: ["Prince Rogers Nelson"] },
      { wiki: "Whitney_Houston" },
      { wiki: "Mariah_Carey" },
      { wiki: "Britney_Spears" },
      { wiki: "Justin_Timberlake" },
      { wiki: "Jay-Z", aliases: ["Jay Z"], deep: ["Shawn Carter"] },
      { wiki: "Doja_Cat", deep: ["Amala Dlamini"] },
      { wiki: "Chappell_Roan", deep: ["Kayleigh Amstutz"] },
      { wiki: "Lana_Del_Rey", deep: ["Elizabeth Grant", "Lizzy Grant"] },
      { wiki: "Stevie_Wonder", deep: ["Stevland Morris"] },
      { wiki: "Frank_Sinatra" },
      { wiki: "Lizzo", deep: ["Melissa Jefferson"] },
      { wiki: "SZA", deep: ["Solána Rowe"] },
      { wiki: "Tupac_Shakur", aliases: ["Tupac", "2Pac"] },
      { wiki: "Travis_Scott", deep: ["Jacques Webster"] },
    ],
    // Hard mode: recognizable, but not household names.
    hard: [
      { wiki: "Hozier", deep: ["Andrew Hozier-Byrne"] },
      { wiki: "Florence_Welch" },
      { wiki: "Lorde", deep: ["Ella Yelich-O'Connor"] },
      { wiki: "Björk", aliases: ["Bjork"], deep: ["Björk Guðmundsdóttir"] },
      { wiki: "Grimes", deep: ["Claire Boucher"] },
      { wiki: "Phoebe_Bridgers" },
      { wiki: "Mitski" },
      { wiki: "Fiona_Apple" },
      { wiki: "Janelle_Monáe", aliases: ["Janelle Monae"] },
      { wiki: "FKA_Twigs", deep: ["Tahliah Barnett"] },
      { wiki: "Solange_Knowles", aliases: ["Solange"] },
      { wiki: "Erykah_Badu", deep: ["Erica Wright"] },
      { wiki: "Lauryn_Hill" },
      { wiki: "Missy_Elliott", aliases: ["Missy"] },
      { wiki: "Busta_Rhymes", deep: ["Trevor Smith"] },
      { wiki: "Nas", deep: ["Nasir Jones"] },
      { wiki: "Tyler,_the_Creator", aliases: ["Tyler the Creator"], deep: ["Tyler Okonma"] },
      { wiki: "Frank_Ocean", deep: ["Christopher Breaux"] },
      { wiki: "Donald_Glover", aliases: ["Childish Gambino"] },
      { wiki: "Anderson_.Paak", aliases: ["Anderson Paak"], deep: ["Brandon Anderson"] },
      { wiki: "Thom_Yorke" },
      { wiki: "Chris_Martin" },
      { wiki: "Dave_Grohl" },
      { wiki: "Jack_White" },
      { wiki: "Debbie_Harry" },
      { wiki: "Stevie_Nicks" },
      { wiki: "Patti_Smith" },
      { wiki: "Joni_Mitchell" },
      { wiki: "Leonard_Cohen" },
      { wiki: "Tom_Waits" },
      { wiki: "Nick_Cave" },
      { wiki: "Iggy_Pop", deep: ["James Osterberg"] },
      { wiki: "Ozzy_Osbourne", aliases: ["Ozzy"] },
      { wiki: "Robert_Plant" },
      { wiki: "Jimmy_Page" },
      { wiki: "Keith_Richards" },
      { wiki: "Bruce_Springsteen", aliases: ["The Boss"] },
      { wiki: "Johnny_Cash" },
      { wiki: "Willie_Nelson" },
      { wiki: "Chris_Stapleton" },
      { wiki: "Kacey_Musgraves" },
      { wiki: "Zach_Bryan" },
      { wiki: "Luke_Combs" },
      { wiki: "Burna_Boy", deep: ["Damini Ogulu"] },
      { wiki: "Wizkid", deep: ["Ayodeji Balogun"] },
      { wiki: "Tems", deep: ["Temilade Openiyi"] },
      { wiki: "Rosalía", aliases: ["Rosalia"] },
      { wiki: "Karol_G", deep: ["Carolina Giraldo"] },
      { wiki: "J_Balvin", deep: ["José Osorio"] },
      { wiki: "Peso_Pluma", deep: ["Hassan Kabande"] },
      { wiki: "Stromae", deep: ["Paul Van Haver"] },
      { wiki: "Lisa_(rapper)", aliases: ["Lalisa"], deep: ["Lalisa Manobal"] },
      { wiki: "Jung_Kook", aliases: ["Jungkook"], deep: ["Jeon Jungkook", "Jeon Jung-kook"] },
      { wiki: "Charli_XCX", aliases: ["Charli"], deep: ["Charlotte Aitchison"] },
      { wiki: "Troye_Sivan" },
      { wiki: "Kali_Uchis" },
      { wiki: "Questlove", deep: ["Ahmir Thompson"] },
      { wiki: "Pharrell_Williams", aliases: ["Pharrell"] },
      { wiki: "Lil_Wayne", deep: ["Dwayne Carter"] },
      { wiki: "Kid_Cudi", deep: ["Scott Mescudi"] },
      { wiki: "Mac_Miller", deep: ["Malcolm McCormick"] },
      { wiki: "Amy_Winehouse" },
      { wiki: "Kurt_Cobain" },
      { wiki: "Jimi_Hendrix" },
      { wiki: "Janis_Joplin" },
      { wiki: "Aretha_Franklin" },
      { wiki: "Nina_Simone" },
      { wiki: "Ray_Charles" },
      { wiki: "James_Brown" },
      { wiki: "Chuck_Berry" },
      { wiki: "Tina_Turner" },
      { wiki: "Cher", deep: ["Cherilyn Sarkisian"] },
      { wiki: "Sting_(musician)", deep: ["Gordon Sumner"] },
      { wiki: "Bono", deep: ["Paul Hewson"] },
      { wiki: "Phil_Collins" },
      { wiki: "Rod_Stewart" },
      { wiki: "Billy_Joel" },
      { wiki: "Lionel_Richie" },
    ],
  },
  sports: {
    label: "Sports",
    emoji: "🏆",
    people: [
      { wiki: "Lionel_Messi", aliases: ["Messi"] },
      { wiki: "Cristiano_Ronaldo", aliases: ["Ronaldo", "CR7"] },
      { wiki: "Serena_Williams" },
      { wiki: "LeBron_James", aliases: ["LeBron"] },
      { wiki: "Usain_Bolt" },
      { wiki: "Roger_Federer" },
      { wiki: "Michael_Jordan" },
      { wiki: "Simone_Biles" },
      { wiki: "Neymar" },
      { wiki: "Kylian_Mbappé", aliases: ["Kylian Mbappe", "Mbappe"] },
      { wiki: "Stephen_Curry", aliases: ["Steph Curry"] },
      { wiki: "Tom_Brady" },
      { wiki: "Rafael_Nadal" },
      { wiki: "Novak_Djokovic" },
      { wiki: "Lewis_Hamilton" },
      { wiki: "Tiger_Woods", deep: ["Eldrick Woods"] },
      { wiki: "Muhammad_Ali", deep: ["Cassius Clay"] },
      { wiki: "Michael_Phelps" },
      { wiki: "Naomi_Osaka" },
      { wiki: "Conor_McGregor" },
      { wiki: "Shohei_Ohtani" },
      { wiki: "Kobe_Bryant", aliases: ["Kobe"] },
      { wiki: "Pelé", aliases: ["Pele"], deep: ["Edson Arantes do Nascimento", "Edson Nascimento"] },
      { wiki: "Zlatan_Ibrahimović", aliases: ["Zlatan", "Zlatan Ibrahimovic", "Ibrahimovic"] },
      { wiki: "Erling_Haaland" },
      { wiki: "Caitlin_Clark" },
      { wiki: "Patrick_Mahomes" },
      { wiki: "Travis_Kelce" },
      { wiki: "Wayne_Gretzky" },
      { wiki: "Mike_Tyson" },
      { wiki: "David_Beckham" },
      { wiki: "Max_Verstappen" },
      { wiki: "Giannis_Antetokounmpo", aliases: ["Giannis"] },
      { wiki: "Kevin_Durant" },
      { wiki: "Shaquille_O'Neal", aliases: ["Shaq"] },
      { wiki: "Magic_Johnson", aliases: ["Magic"], deep: ["Earvin Johnson"] },
      { wiki: "Babe_Ruth", deep: ["George Herman Ruth", "George Ruth"] },
      { wiki: "Aaron_Judge" },
      { wiki: "Kevin_De_Bruyne", aliases: ["De Bruyne"] },
      { wiki: "Mohamed_Salah" },
      { wiki: "Luka_Dončić", aliases: ["Luka Doncic", "Doncic", "Luka"] },
      { wiki: "Victor_Wembanyama", aliases: ["Wemby"] },
      { wiki: "Sidney_Crosby" },
      { wiki: "Coco_Gauff" },
      { wiki: "Carlos_Alcaraz" },
      { wiki: "Maria_Sharapova" },
      { wiki: "Floyd_Mayweather_Jr.", aliases: ["Floyd Mayweather"] },
      { wiki: "Diego_Maradona", aliases: ["Maradona"] },
      { wiki: "Zinedine_Zidane", aliases: ["Zidane"] },
      { wiki: "Ronaldinho", deep: ["Ronaldo de Assis Moreira"] },
      { wiki: "Megan_Rapinoe" },
      { wiki: "Nikola_Jokić", aliases: ["Nikola Jokic", "Jokic"] },
    ],
    // Hard mode: recognizable, but not household names.
    hard: [
      { wiki: "Andy_Murray" },
      { wiki: "Stan_Wawrinka" },
      { wiki: "Jannik_Sinner" },
      { wiki: "Iga_Świątek", aliases: ["Iga Swiatek", "Swiatek"] },
      { wiki: "Aryna_Sabalenka" },
      { wiki: "Venus_Williams" },
      { wiki: "Billie_Jean_King" },
      { wiki: "Martina_Navratilova" },
      { wiki: "Andre_Agassi" },
      { wiki: "Pete_Sampras" },
      { wiki: "Steffi_Graf" },
      { wiki: "Luka_Modrić", aliases: ["Luka Modric", "Modric"] },
      { wiki: "Robert_Lewandowski" },
      { wiki: "Harry_Kane" },
      { wiki: "Jude_Bellingham" },
      { wiki: "Vinícius_Júnior", aliases: ["Vinicius Junior", "Vinicius Jr", "Vini Jr", "Vinicius"] },
      { wiki: "Thierry_Henry" },
      { wiki: "Andrea_Pirlo" },
      { wiki: "Gianluigi_Buffon" },
      { wiki: "Sergio_Ramos" },
      { wiki: "Andrés_Iniesta", aliases: ["Andres Iniesta"] },
      { wiki: "Wayne_Rooney" },
      { wiki: "Steven_Gerrard" },
      { wiki: "Didier_Drogba" },
      { wiki: "Alex_Morgan" },
      { wiki: "Marta_(footballer)", deep: ["Marta Vieira da Silva"] },
      { wiki: "Lamine_Yamal" },
      { wiki: "Jayson_Tatum" },
      { wiki: "Anthony_Edwards_(basketball)", aliases: ["Ant Edwards"] },
      { wiki: "Joel_Embiid" },
      { wiki: "Ja_Morant" },
      { wiki: "Kawhi_Leonard", aliases: ["Kawhi"] },
      { wiki: "Dirk_Nowitzki", aliases: ["Dirk"] },
      { wiki: "Tim_Duncan" },
      { wiki: "Allen_Iverson" },
      { wiki: "Dennis_Rodman" },
      { wiki: "Larry_Bird" },
      { wiki: "Kareem_Abdul-Jabbar", aliases: ["Kareem", "Kareem Abdul Jabbar"], deep: ["Lew Alcindor"] },
      { wiki: "Peyton_Manning" },
      { wiki: "Aaron_Rodgers" },
      { wiki: "Josh_Allen" },
      { wiki: "Lamar_Jackson" },
      { wiki: "Jerry_Rice" },
      { wiki: "Derek_Jeter" },
      { wiki: "Mookie_Betts" },
      { wiki: "Alexander_Ovechkin", aliases: ["Alex Ovechkin"] },
      { wiki: "Connor_McDavid" },
      { wiki: "Mario_Lemieux" },
      { wiki: "Fernando_Alonso" },
      { wiki: "Charles_Leclerc" },
      { wiki: "Lando_Norris" },
      { wiki: "Michael_Schumacher" },
      { wiki: "Ayrton_Senna" },
      { wiki: "Sebastian_Vettel" },
      { wiki: "Valentino_Rossi" },
      { wiki: "Rory_McIlroy" },
      { wiki: "Scottie_Scheffler" },
      { wiki: "Phil_Mickelson" },
      { wiki: "Jon_Jones" },
      { wiki: "Khabib_Nurmagomedov", aliases: ["Khabib"] },
      { wiki: "Ronda_Rousey" },
      { wiki: "Israel_Adesanya" },
      { wiki: "Manny_Pacquiao" },
      { wiki: "Canelo_Álvarez", aliases: ["Canelo", "Canelo Alvarez"], deep: ["Saúl Álvarez"] },
      { wiki: "Tyson_Fury" },
      { wiki: "Katie_Ledecky" },
      { wiki: "Armand_Duplantis", aliases: ["Mondo Duplantis", "Mondo"] },
      { wiki: "Eliud_Kipchoge" },
      { wiki: "Sha'Carri_Richardson", aliases: ["ShaCarri Richardson"] },
      { wiki: "Noah_Lyles" },
      { wiki: "Sachin_Tendulkar", aliases: ["Sachin"] },
      { wiki: "Virat_Kohli" },
      { wiki: "MS_Dhoni", aliases: ["Dhoni"] },
      { wiki: "Tony_Hawk" },
      { wiki: "Shaun_White" },
      { wiki: "Lindsey_Vonn" },
      { wiki: "Mikaela_Shiffrin" },
    ],
  },
  public: {
    label: "Public Figures",
    emoji: "🌍",
    people: [
      { wiki: "Oprah_Winfrey", aliases: ["Oprah"] },
      { wiki: "Barack_Obama", aliases: ["Obama"] },
      { wiki: "Michelle_Obama" },
      { wiki: "Elon_Musk" },
      { wiki: "Kim_Kardashian" },
      { wiki: "Kylie_Jenner" },
      { wiki: "Bill_Gates" },
      { wiki: "Mark_Zuckerberg", aliases: ["Zuck"] },
      { wiki: "Jeff_Bezos" },
      { wiki: "Steve_Jobs" },
      { wiki: "Donald_Trump", aliases: ["Trump"] },
      { wiki: "Joe_Biden", aliases: ["Biden"] },
      { wiki: "Ellen_DeGeneres", aliases: ["Ellen"] },
      { wiki: "Gordon_Ramsay" },
      { wiki: "Greta_Thunberg" },
      { wiki: "MrBeast", aliases: ["Mr Beast"], deep: ["Jimmy Donaldson"] },
      { wiki: "Kamala_Harris" },
      { wiki: "Warren_Buffett" },
      { wiki: "Martin_Luther_King_Jr.", aliases: ["MLK", "Martin Luther King"] },
      { wiki: "Albert_Einstein", aliases: ["Einstein"] },
      { wiki: "Nelson_Mandela" },
      { wiki: "Mahatma_Gandhi", aliases: ["Gandhi"], deep: ["Mohandas Gandhi", "Mohandas Karamchand Gandhi"] },
      { wiki: "Stephen_Hawking" },
      { wiki: "Neil_Armstrong" },
      { wiki: "Richard_Branson" },
      { wiki: "Martha_Stewart" },
      { wiki: "Jimmy_Fallon" },
      { wiki: "Paris_Hilton" },
      { wiki: "Anthony_Bourdain" },
      { wiki: "Khaby_Lame" },
      { wiki: "Pope_Francis", deep: ["Jorge Mario Bergoglio", "Jorge Bergoglio"] },
      { wiki: "Malala_Yousafzai", aliases: ["Malala"] },
      { wiki: "Abraham_Lincoln", aliases: ["Lincoln", "Abe Lincoln"] },
      { wiki: "Bernie_Sanders", aliases: ["Bernie"] },
      { wiki: "Hillary_Clinton", aliases: ["Hillary"] },
      { wiki: "Bill_Clinton" },
      { wiki: "Vladimir_Putin" },
      { wiki: "Emmanuel_Macron" },
      { wiki: "Justin_Trudeau" },
      { wiki: "Volodymyr_Zelenskyy", aliases: ["Zelensky", "Zelenskiy", "Volodymyr Zelensky"] },
      { wiki: "Narendra_Modi" },
      { wiki: "Tim_Cook" },
      { wiki: "Sam_Altman" },
      { wiki: "Jensen_Huang" },
      { wiki: "Joe_Rogan" },
      { wiki: "Kai_Cenat" },
      { wiki: "Kris_Jenner" },
      { wiki: "Anna_Wintour" },
      { wiki: "Frida_Kahlo" },
      { wiki: "Pablo_Picasso", aliases: ["Picasso"] },
    ],
    // Hard mode: recognizable, but not household names.
    hard: [
      { wiki: "Angela_Merkel" },
      { wiki: "Jacinda_Ardern" },
      { wiki: "Keir_Starmer" },
      { wiki: "Rishi_Sunak" },
      { wiki: "Boris_Johnson" },
      { wiki: "Xi_Jinping" },
      { wiki: "Kim_Jong_Un", aliases: ["Kim Jong-un"] },
      { wiki: "Recep_Tayyip_Erdoğan", aliases: ["Erdogan", "Recep Tayyip Erdogan"] },
      { wiki: "Luiz_Inácio_Lula_da_Silva", aliases: ["Lula", "Lula da Silva"] },
      { wiki: "Javier_Milei" },
      { wiki: "Claudia_Sheinbaum" },
      { wiki: "Giorgia_Meloni" },
      { wiki: "Olaf_Scholz" },
      { wiki: "Benjamin_Netanyahu", aliases: ["Netanyahu", "Bibi"] },
      { wiki: "Nancy_Pelosi" },
      { wiki: "Alexandria_Ocasio-Cortez", aliases: ["AOC", "Ocasio-Cortez", "Alexandria Ocasio Cortez"] },
      { wiki: "Mitch_McConnell" },
      { wiki: "Ruth_Bader_Ginsburg", aliases: ["RBG"] },
      { wiki: "JD_Vance", aliases: ["J D Vance"] },
      { wiki: "Ron_DeSantis" },
      { wiki: "Gavin_Newsom" },
      { wiki: "Pete_Buttigieg" },
      { wiki: "Jimmy_Carter" },
      { wiki: "Ronald_Reagan" },
      { wiki: "John_F._Kennedy", aliases: ["JFK", "John F Kennedy", "John Kennedy"] },
      { wiki: "Winston_Churchill" },
      { wiki: "Margaret_Thatcher" },
      { wiki: "Satya_Nadella" },
      { wiki: "Sundar_Pichai" },
      { wiki: "Jack_Dorsey" },
      { wiki: "Larry_Page" },
      { wiki: "Sergey_Brin" },
      { wiki: "Sheryl_Sandberg" },
      { wiki: "Reed_Hastings" },
      { wiki: "Jack_Ma" },
      { wiki: "Mukesh_Ambani" },
      { wiki: "Bernard_Arnault" },
      { wiki: "Larry_Ellison" },
      { wiki: "Steve_Wozniak", aliases: ["Woz"] },
      { wiki: "Michael_Bloomberg" },
      { wiki: "Mark_Cuban" },
      { wiki: "Lisa_Su" },
      { wiki: "Neil_deGrasse_Tyson", aliases: ["Neil deGrasse Tyson"] },
      { wiki: "Bill_Nye" },
      { wiki: "Jane_Goodall" },
      { wiki: "David_Attenborough" },
      { wiki: "Carl_Sagan" },
      { wiki: "Marie_Curie" },
      { wiki: "Nikola_Tesla" },
      { wiki: "Andy_Warhol" },
      { wiki: "Salvador_Dalí", aliases: ["Salvador Dali", "Dali"] },
      { wiki: "Anderson_Cooper" },
      { wiki: "Stephen_Colbert" },
      { wiki: "Jimmy_Kimmel" },
      { wiki: "John_Oliver" },
      { wiki: "Trevor_Noah" },
      { wiki: "Conan_O'Brien", aliases: ["Conan"] },
      { wiki: "David_Letterman" },
      { wiki: "Jon_Stewart" },
      { wiki: "Howard_Stern" },
      { wiki: "Guy_Fieri" },
      { wiki: "Jamie_Oliver" },
      { wiki: "PewDiePie", deep: ["Felix Kjellberg"] },
      { wiki: "Marques_Brownlee", aliases: ["MKBHD"] },
      { wiki: "Charli_D'Amelio" },
      { wiki: "Logan_Paul" },
      { wiki: "IShowSpeed", aliases: ["Speed"], deep: ["Darren Watkins"] },
      { wiki: "Emma_Chamberlain" },
      { wiki: "14th_Dalai_Lama", aliases: ["Dalai Lama"], deep: ["Tenzin Gyatso"] },
    ],
  },
};
