// Celebrities grouped by category. Each entry: the Wikipedia page title
// (used to fetch the photo) and optional extra accepted answers.
const CATEGORIES = {
  movies: {
    label: "Movies & TV",
    emoji: "🎬",
    people: [
      { wiki: "Tom_Hanks" },
      { wiki: "Leonardo_DiCaprio", aliases: ["Leo DiCaprio"] },
      { wiki: "Dwayne_Johnson", aliases: ["The Rock"] },
      { wiki: "Brad_Pitt" },
      { wiki: "Angelina_Jolie" },
      { wiki: "Keanu_Reeves" },
      { wiki: "Scarlett_Johansson" },
      { wiki: "Morgan_Freeman" },
      { wiki: "Meryl_Streep" },
      { wiki: "Will_Smith" },
      { wiki: "Zendaya" },
      { wiki: "Timothée_Chalamet", aliases: ["Timothee Chalamet"] },
      { wiki: "Margot_Robbie" },
      { wiki: "Ryan_Gosling" },
      { wiki: "Ryan_Reynolds" },
      { wiki: "Emma_Watson" },
      { wiki: "Daniel_Radcliffe" },
      { wiki: "Robert_Downey_Jr.", aliases: ["Robert Downey Jr", "RDJ", "Robert Downey"] },
      { wiki: "Chris_Hemsworth" },
      { wiki: "Tom_Cruise" },
      { wiki: "Denzel_Washington" },
      { wiki: "Samuel_L._Jackson", aliases: ["Samuel Jackson", "Samuel L Jackson"] },
      { wiki: "Jennifer_Lawrence" },
      { wiki: "Natalie_Portman" },
      { wiki: "Pedro_Pascal" },
      { wiki: "Keira_Knightley" },
      { wiki: "Hugh_Jackman" },
      { wiki: "Johnny_Depp" },
      { wiki: "Nicole_Kidman" },
      { wiki: "Jackie_Chan" },
      { wiki: "Tom_Holland" },
      { wiki: "Jennifer_Aniston" },
      { wiki: "Chris_Pratt" },
      { wiki: "Julia_Roberts" },
      { wiki: "George_Clooney" },
      { wiki: "Matt_Damon" },
      { wiki: "Sandra_Bullock" },
      { wiki: "Harrison_Ford" },
      { wiki: "Arnold_Schwarzenegger", aliases: ["Arnold", "Schwarzenegger"] },
      { wiki: "Sydney_Sweeney" },
      { wiki: "Anne_Hathaway" },
      { wiki: "Florence_Pugh" },
      { wiki: "Jason_Momoa" },
      { wiki: "Cillian_Murphy" },
      { wiki: "Emma_Stone" },
      { wiki: "Viola_Davis" },
      { wiki: "Idris_Elba" },
      { wiki: "Chris_Evans_(actor)" },
      { wiki: "Mark_Ruffalo" },
      { wiki: "Benedict_Cumberbatch" },
      { wiki: "Tom_Hardy" },
      { wiki: "Christian_Bale" },
      { wiki: "Jim_Carrey" },
      { wiki: "Adam_Sandler" },
      { wiki: "Eddie_Murphy" },
      { wiki: "Kevin_Hart" },
      { wiki: "Halle_Berry" },
      { wiki: "Charlize_Theron" },
      { wiki: "Kate_Winslet" },
      { wiki: "Cate_Blanchett" },
      { wiki: "Nicolas_Cage" },
      { wiki: "Al_Pacino" },
      { wiki: "Robert_De_Niro", aliases: ["De Niro"] },
      { wiki: "Jenna_Ortega" },
      { wiki: "Millie_Bobby_Brown" },
      { wiki: "Austin_Butler" },
      { wiki: "Paul_Rudd" },
      { wiki: "Steve_Carell" },
      { wiki: "Marilyn_Monroe" },
      { wiki: "Audrey_Hepburn" },
      { wiki: "Charlie_Chaplin" },
    ],
  },
  music: {
    label: "Music",
    emoji: "🎤",
    people: [
      { wiki: "Taylor_Swift" },
      { wiki: "Beyoncé", aliases: ["Beyonce", "Queen B"] },
      { wiki: "Rihanna" },
      { wiki: "Lady_Gaga" },
      { wiki: "Jennifer_Lopez", aliases: ["J.Lo", "JLo"] },
      { wiki: "Ed_Sheeran" },
      { wiki: "Adele" },
      { wiki: "Billie_Eilish" },
      { wiki: "Ariana_Grande" },
      { wiki: "Justin_Bieber" },
      { wiki: "Bruno_Mars" },
      { wiki: "Snoop_Dogg", aliases: ["Snoop"] },
      { wiki: "Selena_Gomez" },
      { wiki: "Harry_Styles" },
      { wiki: "Dua_Lipa" },
      { wiki: "Paul_McCartney" },
      { wiki: "Dolly_Parton" },
      { wiki: "Shakira" },
      { wiki: "Bad_Bunny" },
      { wiki: "Michael_Jackson" },
      { wiki: "Drake_(musician)" },
      { wiki: "Eminem" },
      { wiki: "Kanye_West", aliases: ["Kanye", "Ye"] },
      { wiki: "Madonna" },
      { wiki: "Elton_John" },
      { wiki: "Olivia_Rodrigo" },
      { wiki: "Sabrina_Carpenter" },
      { wiki: "Post_Malone" },
      { wiki: "Katy_Perry" },
      { wiki: "Miley_Cyrus" },
      { wiki: "Mick_Jagger" },
      { wiki: "Nicki_Minaj" },
      { wiki: "The_Weeknd", aliases: ["Weeknd"] },
      { wiki: "Elvis_Presley", aliases: ["Elvis"] },
      { wiki: "Freddie_Mercury" },
      { wiki: "Kendrick_Lamar", aliases: ["Kendrick"] },
      { wiki: "Bob_Marley" },
      { wiki: "Bob_Dylan" },
      { wiki: "John_Lennon" },
      { wiki: "David_Bowie" },
      { wiki: "Prince_(musician)" },
      { wiki: "Whitney_Houston" },
      { wiki: "Mariah_Carey" },
      { wiki: "Britney_Spears" },
      { wiki: "Justin_Timberlake" },
      { wiki: "Jay-Z", aliases: ["Jay Z"] },
      { wiki: "Doja_Cat" },
      { wiki: "Chappell_Roan" },
      { wiki: "Lana_Del_Rey" },
      { wiki: "Stevie_Wonder" },
      { wiki: "Frank_Sinatra" },
      { wiki: "Lizzo" },
      { wiki: "SZA" },
      { wiki: "Tupac_Shakur", aliases: ["Tupac", "2Pac"] },
      { wiki: "Travis_Scott" },
    ],
  },
  sports: {
    label: "Sports",
    emoji: "🏆",
    people: [
      { wiki: "Lionel_Messi", aliases: ["Messi"] },
      { wiki: "Cristiano_Ronaldo", aliases: ["Ronaldo", "CR7"] },
      { wiki: "Serena_Williams" },
      { wiki: "LeBron_James", aliases: ["LeBron"] },
      { wiki: "Usain_Bolt" },
      { wiki: "Roger_Federer" },
      { wiki: "Michael_Jordan" },
      { wiki: "Simone_Biles" },
      { wiki: "Neymar" },
      { wiki: "Kylian_Mbappé", aliases: ["Kylian Mbappe", "Mbappe"] },
      { wiki: "Stephen_Curry", aliases: ["Steph Curry"] },
      { wiki: "Tom_Brady" },
      { wiki: "Rafael_Nadal" },
      { wiki: "Novak_Djokovic" },
      { wiki: "Lewis_Hamilton" },
      { wiki: "Tiger_Woods" },
      { wiki: "Muhammad_Ali" },
      { wiki: "Michael_Phelps" },
      { wiki: "Naomi_Osaka" },
      { wiki: "Conor_McGregor" },
      { wiki: "Shohei_Ohtani" },
      { wiki: "Kobe_Bryant", aliases: ["Kobe"] },
      { wiki: "Pelé", aliases: ["Pele"] },
      { wiki: "Zlatan_Ibrahimović", aliases: ["Zlatan", "Zlatan Ibrahimovic", "Ibrahimovic"] },
      { wiki: "Erling_Haaland" },
      { wiki: "Caitlin_Clark" },
      { wiki: "Patrick_Mahomes" },
      { wiki: "Travis_Kelce" },
      { wiki: "Wayne_Gretzky" },
      { wiki: "Mike_Tyson" },
      { wiki: "David_Beckham" },
      { wiki: "Max_Verstappen" },
      { wiki: "Giannis_Antetokounmpo", aliases: ["Giannis"] },
      { wiki: "Kevin_Durant" },
      { wiki: "Shaquille_O'Neal", aliases: ["Shaq"] },
      { wiki: "Magic_Johnson", aliases: ["Magic"] },
      { wiki: "Babe_Ruth" },
      { wiki: "Aaron_Judge" },
      { wiki: "Kevin_De_Bruyne", aliases: ["De Bruyne"] },
      { wiki: "Mohamed_Salah" },
      { wiki: "Luka_Dončić", aliases: ["Luka Doncic", "Doncic", "Luka"] },
      { wiki: "Victor_Wembanyama", aliases: ["Wemby"] },
      { wiki: "Sidney_Crosby" },
      { wiki: "Coco_Gauff" },
      { wiki: "Carlos_Alcaraz" },
      { wiki: "Maria_Sharapova" },
      { wiki: "Floyd_Mayweather_Jr.", aliases: ["Floyd Mayweather"] },
      { wiki: "Diego_Maradona", aliases: ["Maradona"] },
      { wiki: "Zinedine_Zidane", aliases: ["Zidane"] },
      { wiki: "Ronaldinho" },
      { wiki: "Megan_Rapinoe" },
      { wiki: "Nikola_Jokić", aliases: ["Nikola Jokic", "Jokic"] },
    ],
  },
  public: {
    label: "Public Figures",
    emoji: "🌍",
    people: [
      { wiki: "Oprah_Winfrey", aliases: ["Oprah"] },
      { wiki: "Barack_Obama", aliases: ["Obama"] },
      { wiki: "Michelle_Obama" },
      { wiki: "Elon_Musk" },
      { wiki: "Kim_Kardashian" },
      { wiki: "Kylie_Jenner" },
      { wiki: "Bill_Gates" },
      { wiki: "Mark_Zuckerberg", aliases: ["Zuck"] },
      { wiki: "Jeff_Bezos" },
      { wiki: "Steve_Jobs" },
      { wiki: "Donald_Trump", aliases: ["Trump"] },
      { wiki: "Joe_Biden", aliases: ["Biden"] },
      { wiki: "Ellen_DeGeneres", aliases: ["Ellen"] },
      { wiki: "Gordon_Ramsay" },
      { wiki: "Greta_Thunberg" },
      { wiki: "MrBeast", aliases: ["Mr Beast", "Jimmy Donaldson"] },
      { wiki: "Kamala_Harris" },
      { wiki: "Warren_Buffett" },
      { wiki: "Martin_Luther_King_Jr.", aliases: ["MLK", "Martin Luther King"] },
      { wiki: "Albert_Einstein", aliases: ["Einstein"] },
      { wiki: "Nelson_Mandela" },
      { wiki: "Mahatma_Gandhi", aliases: ["Gandhi"] },
      { wiki: "Stephen_Hawking" },
      { wiki: "Neil_Armstrong" },
      { wiki: "Richard_Branson" },
      { wiki: "Martha_Stewart" },
      { wiki: "Jimmy_Fallon" },
      { wiki: "Paris_Hilton" },
      { wiki: "Anthony_Bourdain" },
      { wiki: "Khaby_Lame" },
      { wiki: "Pope_Francis" },
      { wiki: "Malala_Yousafzai", aliases: ["Malala"] },
      { wiki: "Abraham_Lincoln", aliases: ["Lincoln", "Abe Lincoln"] },
      { wiki: "Bernie_Sanders", aliases: ["Bernie"] },
      { wiki: "Hillary_Clinton", aliases: ["Hillary"] },
      { wiki: "Bill_Clinton" },
      { wiki: "Vladimir_Putin" },
      { wiki: "Emmanuel_Macron" },
      { wiki: "Justin_Trudeau" },
      { wiki: "Volodymyr_Zelenskyy", aliases: ["Zelensky", "Zelenskiy", "Volodymyr Zelensky"] },
      { wiki: "Narendra_Modi" },
      { wiki: "Tim_Cook" },
      { wiki: "Sam_Altman" },
      { wiki: "Jensen_Huang" },
      { wiki: "Joe_Rogan" },
      { wiki: "Kai_Cenat" },
      { wiki: "Kris_Jenner" },
      { wiki: "Anna_Wintour" },
      { wiki: "Frida_Kahlo" },
      { wiki: "Pablo_Picasso", aliases: ["Picasso"] },
    ],
  },
};
